DBAAS-530: create instance page changes
RHEcosystemAppEng/dbaas-dynamic-plugin pull request #122
Opened 2022-05-13 18:10 UTC by olavtar

Jira: https://issues.redhat.com/browse/DBAAS-530
Modified the create instance page based on the new UXD design.

Signed-off-by: Olga Lavtar <olavtar@redhat.com>

2022-05-13 19:52 UTC, yzhao583 requested changes
@olavtar We should not remove the disable provider account related logic, since it is required for developer to create database instance.

2022-05-13 19:52 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> -  const [isDBProviderFieldDisabled, setIsDBProviderFieldDisabled] = React.useState(false)
@olavtar Why this is removed? This is required for developer create db instance.

2022-05-13 19:52 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> -  const [isInventoryFieldDisabled, setIsInventoryFieldDisabled] = React.useState(false)
@olavtar Same with above.

2022-05-13 19:52 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> -      setIsDBProviderFieldDisabled(true)
@olavtar Same here

2022-05-13 19:52 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> -      setIsInventoryFieldDisabled(true)
@olavtar Same here

2022-05-13 19:52 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> -                    isDisabled={isInventoryFieldDisabled}
@olavtar Same here

2022-05-13 20:04 UTC, olavtar commented on src/components/providerClusterProvisionPage.jsx
> -  const [isDBProviderFieldDisabled, setIsDBProviderFieldDisabled] = React.useState(false)
DBProviderField is completely removed from the page.

2022-05-13 20:06 UTC, olavtar commented on src/components/providerClusterProvisionPage.jsx
> -  const [isInventoryFieldDisabled, setIsInventoryFieldDisabled] = React.useState(false)
@yzhao583  InventoryField is Enabled in the new design, so they can change the provider account on the instance page.

2022-05-13 22:23 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> -  const [isInventoryFieldDisabled, setIsInventoryFieldDisabled] = React.useState(false)
@olavtar This page is used by developer as well, from the [design](https://marvelapp.com/prototype/16dd9cj9/screen/84713496), we can see that the Provider account field is disabled when developer create instance.

2022-05-16 13:53 UTC, yzhao583 approved these changes

2022-05-16 17:40 UTC, yzhao583 approved these changes

2022-05-16 18:01 UTC, merged