add support for tenancy and the developer persona
RHEcosystemAppEng/dbaas-dynamic-plugin pull request #18
Opened 2021-08-27 20:35 UTC by tchughesiv

![Screen Shot 2021-08-27 at 2 05 02 PM](https://user-images.githubusercontent.com/11095048/131188497-bba0c740-7de2-4276-b29c-c97afb719c36.png)

2021-08-31 16:38 UTC, yzhao583 requested changes

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +  async function fetchInventoryItems() {
@tchughesiv Minor: maybe consider to rename the function to something meaningful? For example, "fetchInventoryByNSAndRules"?

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +        console.error(error)
@tchughesiv Should we show the error msg to users? If so, we can do
`setFetchInstancesFailed(true)`
`setStatusMsg(error)`

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +        console.error(error)
@tchughesiv Same here, display error msg to users?

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +        console.error(error)
@tchughesiv Same here, display error msg to users?

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +        console.error(error)
@tchughesiv Same here, display error msg to users?

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +        console.error(error)
@tchughesiv Same here, display error msg to users?

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +  const parseInventoryRulesReview = (responseJson) => {
@tchughesiv This function looks very similar to the `parseTenantRulesReview ` function, maybe combine them?

2021-08-31 16:38 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +      return Promise.reject(new Error(response.statusText))
@tchughesiv Maybe show error msg to users? And ask them to try again?

2021-08-31 17:02 UTC, tchughesiv commented on src/components/instanceListPage.jsx
> +        console.error(error)
I'm honestly not sure... is that the preference? to show the error to users?

2021-08-31 17:57 UTC, tchughesiv commented on src/components/instanceListPage.jsx
> +        console.error(error)
done

2021-08-31 18:02 UTC, yzhao583 approved these changes

2021-08-31 18:18 UTC, tchughesiv commented on src/components/instanceListPage.jsx
> +      return Promise.reject(new Error(response.statusText))
with the other changes i made, it seems this will be shown to users with try again. correct?

2021-09-01 14:16 UTC, jeremyary approved these changes

2021-09-01 15:50 UTC, yzhao583 commented on src/components/instanceListPage.jsx
> +      return Promise.reject(new Error(response.statusText))
Yes, I think so, but maybe we can do some tests.

2021-09-02 16:36 UTC, yzhao583 commented
@jeremyary @tchughesiv Is there any further change for this PR? Can we merge it?

2021-09-02 16:41 UTC, merged