[DBAAS-890] add NS label selector code for valid DBaaSConnection namespaces
RHEcosystemAppEng/dbaas-dynamic-plugin pull request #198
Opened 2022-09-20 20:30 UTC by tchughesiv

2022-09-26 15:12 UTC, yzhao583 requested changes
@tchughesiv Thanks for the contribution! Just some small comments here.

2022-09-26 15:12 UTC, yzhao583 commented on src/utils.ts
> +    console.log('encoded selector = &labelSelector=' + labelSelector)
@tchughesiv Is this for debugging? If so, we may need to remove it.

2022-09-26 15:12 UTC, yzhao583 commented on src/utils.ts
> +  /*
@tchughesiv Do we need this section of code here?

2022-09-26 15:41 UTC, tchughesiv commented on src/utils.ts
> +  /*
yes, still working on replicating that code. this will be removed before i request review. thanks!

2022-09-26 15:41 UTC, tchughesiv commented on src/utils.ts
> +    console.log('encoded selector = &labelSelector=' + labelSelector)
yes, debugging... still working on it

2022-09-26 21:56 UTC, tchughesiv commented on src/utils.ts
> +    console.log('encoded selector = &labelSelector=' + labelSelector)
removed

2022-09-26 21:56 UTC, tchughesiv commented on src/utils.ts
> +  /*
removed

2022-09-28 17:31 UTC, jeremyary approved these changes

2022-09-30 00:20 UTC, merged