add inventory namespace check
RHEcosystemAppEng/dbaas-dynamic-plugin pull request #22
Opened 2021-09-22 18:00 UTC by tchughesiv

If a service admin is in an invalid tenant namespace, they will see this alert when attempting to create an inventory:
![Screen Shot 2021-09-22 at 12 40 09 PM](https://user-images.githubusercontent.com/11095048/134396769-f8913c35-8a8f-442b-8b8e-fd65441cc478.png)

if a user w/ no tenant privileges attempts to create an inventory in an invalid tenant namespace, they will see the following:

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

2021-09-22 18:19 UTC, jeremyary reviewed
Functionally & AFAICT with the code, this is great, thank you! I'll let Yu weigh in on the technical, but lgtm. Verbiage suggestion added, but open to discuss.

2021-09-22 18:19 UTC, jeremyary commented on src/components/providerAccountForm.jsx
> +                Switch to one of these valid namespaces and retry:
This is great! How would you feel about clarifying that it's only invalid for the account part since connections can live anywhere... WDYT about header that says "Invalid Namespace for Provider Account Creation" and subtext "Switch to one of these valid Tenant namespaces and retry"?

2021-09-22 20:18 UTC, jeremyary approved these changes

2021-09-22 21:06 UTC, yzhao583 requested changes
@tchughesiv Thanks for the PR! It looks good to me in general, but just have one small suggestion here.

I pulled your branch and tried it locally, during the testing, I found there is a little flip between the alert and the provider information form.
I was in the namespace 'jary', so I should not see the provider selection form, but I could see it first, and it was replaced by the alerts quickly. 
I guess the reason it that it tooks some time to get the response of the API to fetch namespaces?
A potential solution is that we show a loader if we haven't got response, and after we got response we show the provider selection form or the alert accordingly. WDYT?

2021-09-22 22:03 UTC, tchughesiv commented
@yzhao583 that would be ideal yes… let me see what I can do

2021-09-23 13:10 UTC, jeremyary approved these changes
@yzhao583 please take another look this morning so we can get this promoted if good to go. Thanks!

2021-09-23 14:51 UTC, yzhao583 approved these changes

2021-09-23 14:51 UTC, yzhao583 commented
@jeremyary @tchughesiv Looks good to me

2021-09-23 14:51 UTC, tchughesiv commented
@yzhao583 @jeremyary i've added a delay to the form load which improves the experience, but i think a loader would be the ideal end state in a future PR

2021-09-23 14:53 UTC, merged