Dbaas 237 table to show all connected instance for all db types
RHEcosystemAppEng/dbaas-dynamic-plugin pull request #45
Opened 2022-01-20 18:50 UTC by olavtar

Created new table for admin dashboard to show connections from all projects and inventories.

2022-01-20 19:04 UTC, tchughesiv requested changes

2022-01-20 19:04 UTC, tchughesiv commented on src/components/adminDashboard.jsx
> +  }
@olavtar it seems like we're replicating most of these methods, instead of importing the existing ones from other components... e.g.
https://github.com/tchughesiv/dbaas-dynamic-plugin/blob/f551bf75933fc5868ad4a9005bde4e28ce5a4d01/src/components/providerAccountForm.jsx#L15

could you explore importing these instead?

2022-01-20 21:32 UTC, tchughesiv requested changes

2022-01-20 21:32 UTC, tchughesiv commented on src/components/adminDashboard.jsx
> +  const fetchInstances = async () => {
isn't this method also a duplicate?

2022-01-20 21:32 UTC, tchughesiv commented on src/components/adminDashboard.jsx
> +} from './instanceListPage'
are all of these imports necessary? seems only a few of these are used in this file.
https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/blob/00c4203c7cc6bdc8017902e3e9d4ffacbf7bbf68/src/components/adminDashboard.jsx#L183-L188

2022-01-20 21:32 UTC, tchughesiv commented on src/components/adminDashboard.jsx
> +  const fetchServiceBindings = async () => {
isn't this method also a duplicate?

2022-01-20 21:32 UTC, tchughesiv commented on src/components/adminDashboard.jsx
> +  const fetchDBaaSConnections = async () => {
isn't this method also a duplicate?

2022-01-20 21:54 UTC, olavtar commented on src/components/adminDashboard.jsx
> +} from './instanceListPage'
Let me take another look, see if there are any extra imports.

2022-01-21 17:03 UTC, yzhao583 reviewed
@olavtar Thanks for the PR 👍  The code looks good in general, just couple suggestions here, please check the comments.

2022-01-31 16:07 UTC, tchughesiv approved these changes
lgtm

@olavtar @yzhao583 has this been fully vetted against a dbaas cluster? all pages including existing dev/admin views?

i'm good to merge if @yzhao583 approves

2022-01-31 20:17 UTC, merged