Timeout with the status of the instance being 'Ready'
RHEcosystemAppEng/dbaas-dynamic-plugin pull request #81
Opened 2022-03-03 06:37 UTC by olavtar

Added check for the status before displaying the error in the timeout scenario.

Signed-off-by: Olga Lavtar <olavtar@redhat.com>

2022-03-03 14:21 UTC, xieshenzh requested changes
Thanks. I think we need to let the user know explicitly it is a timeout scenario, and make sure user won't mistake it as creation failure.

2022-03-03 14:21 UTC, xieshenzh commented on src/components/providerClusterProvisionPage.jsx
> +          }, 30000)
In terms of user experience, I guess there should be some guidelines for setting the value of timeout. So we are not supposed to change it in most cases. But I am not sure what is the rule to follow in this case.

2022-03-03 15:51 UTC, yzhao583 requested changes

2022-03-03 15:51 UTC, yzhao583 commented on src/components/providerClusterProvisionPage.jsx
> +          }, 30000)
@olavtar We should not set the interval to 30 seconds, the logic here is that after the provision request sent, every 3 seconds we check the status of the instance

2022-03-03 16:35 UTC, bmozaffa commented
> Thanks. I think we need to let the user know explicitly it is a timeout scenario, and make sure user won't mistake it as creation failure.

I'm a bit confused now. Is a timeout cause by our decision to stop waiting for a response, and if so, what's the threshold? @yzhao583 seems to imply that it's not 3 seconds. I assumed that whatever it is, there would not have been a timeout if we waited a split second longer, given the ready status we see. Is that your assumption too, and if so, doesn't that mean we should ignore the timeout?

2022-03-03 16:53 UTC, xieshenzh commented
> I'm a bit confused now. Is a timeout cause by our decision to stop waiting for a response, and if so, what's the threshold? @yzhao583 seems to imply that it's not 3 seconds. I assumed that whatever it is, there would not have been a timeout if we waited a split second longer, given the ready status we see. Is that your assumption too, and if so, doesn't that mean we should ignore the timeout?

I mean if the status is NOT ready and we don't want the user to wait for the response for user experience purpose, then we should let the users know there won't be any immediate response (i.e. timeout), but they can check the status later to see if the creation succeeds, instead of telling them creation failed.
Another options is like operator installation, there is no timeout. Instead, we update the status of the instance in UI. User can choose to stop receiving updates by refreshing or navigating to other pages.

I am not sure about the threshold. @yzhao583 could you please let us know how it works?

2022-03-03 18:13 UTC, yzhao583 commented
> > Thanks. I think we need to let the user know explicitly it is a timeout scenario, and make sure user won't mistake it as creation failure.
> 
> I'm a bit confused now. Is a timeout cause by our decision to stop waiting for a response, and if so, what's the threshold? @yzhao583 seems to imply that it's not 3 seconds. I assumed that whatever it is, there would not have been a timeout if we waited a split second longer, given the ready status we see. Is that your assumption too, and if so, doesn't that mean we should ignore the timeout?

@bmozaffa Yes, it is our decision to stop waiting for a response, since from the UX perspective, we cannot let the user see the loader for too long time. The threshold is 30 seconds. The 3 seconds is a interval, not timeout, it means we check the status of the resource every 3 seconds, and change the state of the UI based on the status of the resource.

We can ignore the timeout, but users may not see the result at the current page, which is not an ideal UX in my opinion

2022-03-03 18:19 UTC, bmozaffa commented
@yzhao583 Can you walk us through how that happens in the code? Where is the 30-second threshold, and when/where relative to that is the status read? I'm trying to see how it gets "ready" despite timing out, first.

2022-03-03 18:25 UTC, olavtar commented on src/components/providerClusterProvisionPage.jsx
> +          }, 30000)
@yzhao583 I'll change it back to 3 seconds.

2022-03-03 18:38 UTC, xieshenzh commented
> @xieshenzh The way UI works in current implementation is that. After user kicking off the instance provision request, UI call the API, but please note that, the response of this API will not give any status the resource, so every 3 seconds, UI call another API to check the status of the resource, and change the state according to the response.

@yzhao583 So when the second API call returns an instance with status ready, the UI is supposed to stop status checking, and stop the waiting that could cause timeout.

But in Babak's case, the status of the instance is ready, but something still made the `creation failed` error happen.
We guess that's because timeout happened, and would like to understand from the code if timeout could happen when the status is ready, for example in some kind of race condition scenarios.

2022-03-03 19:08 UTC, yzhao583 commented
> > @xieshenzh The way UI works in current implementation is that. After user kicking off the instance provision request, UI call the API, but please note that, the response of this API will not give any status the resource, so every 3 seconds, UI call another API to check the status of the resource, and change the state according to the response.
> 
> @yzhao583 So when the second API call returns an instance with status ready, the UI is supposed to stop status checking, and stop the waiting that could cause timeout.
> 
> But in Babak's case, the status of the instance is ready, but something still made the `creation failed` error happen. We guess that's because timeout happened, and would like to understand from the code if timeout could happen when the status is ready, for example in some kind of race condition scenarios.

@xieshenzh Yes, we missed that part, so I added comment to ask @olavtar to help to add that logic.

2022-03-03 19:08 UTC, olavtar commented
It seems that - if (responseJson?.status?.phase?.toLowerCase() === 'creating') {
                              if (instanceReadyCondition?.status.toLowerCase() === 'false') {
is not the only successful scenario then?

2022-03-03 19:13 UTC, bmozaffa commented
> Yes, there should be another success scenario, which is `if (responseJson?.status?.phase?.toLowerCase() === 'ready') { if (instanceReadyCondition?.status.toLowerCase() === 'true') {`

Trivial point, but why do we need toLowerCase() for all these things? It's not someone typing in a status, so whatever our code provides, why would we not adopt that capitalization scheme?

2022-03-03 19:38 UTC, yzhao583 commented
> 

@bmozaffa Some of the information comes from the provider operator, so we just want to be a little safer, but I agree, we should adopt to the scheme, we will do a clean up later.

2022-03-03 19:52 UTC, yzhao583 approved these changes
LGTM

2022-03-03 19:53 UTC, xieshenzh approved these changes

2022-03-03 21:04 UTC, bmozaffa commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
@olavtar @yzhao583 @xieshenzh is there a scenario where phase is ready, but instance ready condition status is not true? If there isn't, why the extra check. If there is, in that scenario, will I not see the timeout again with a explanation of ready?

2022-03-03 21:37 UTC, xieshenzh commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
There is not such scenario for crunchy and cockroach. In addition, the condition is always false when the phase is `creating`.

I am not sure about mongo as the phase and condition status are updated based on the `AtlasCluster` CR status which is updated by the mongo controllers. @jianrongzhang89 do you have any idea?

2022-03-03 21:59 UTC, jianrongzhang89 commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
@xieshenzh for mongo, if the phase is Ready, the cluster has been successfully provisioned, so there is no need to check InstanceReady.

2022-03-03 22:05 UTC, jianrongzhang89 commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
@xieshenzh An instance can also have "Pending" status, which means provisioning has not been started. How this case is handled?

2022-03-03 22:06 UTC, olavtar commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
@xieshenzh @jianrongzhang89 @bmozaffa @yzhao583 I'll make the change.

2022-03-03 22:41 UTC, bmozaffa commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
Thanks, I assume phase failed also implies status false and the second check is redundant?

Xieshen, post release and low priority, would it not make sense for us to have a well-defined phase and such that we define as constants? For example, if provider phase is "ready" or "Ready" or "OK", we would want to set ours to "Ready"? We could have another field that's providerPhase if we get an unknown value, and then set our phase to "Unknown". This basically needs to happen at some level anyway, but I wonder if it's not a better fit for our operator, rather than the UI which does a case-insensitive comparison in this case.

2022-03-03 23:04 UTC, olavtar commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
@xieshenzh @jianrongzhang89 If the phase 'failed' we are checking provisionReadyCondition. Can the status of provisionReadyCondition can be something other than false? what about instanceReadyCondition?

2022-03-04 00:50 UTC, bmozaffa approved these changes
I think the only remaining question in our conversation was whether the other block also needs to be fixed (is redundant check), but the changes made so far here look good and based on agreement

2022-03-04 00:51 UTC, merged

2022-03-04 02:53 UTC, xieshenzh commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
> Xieshen, post release and low priority, would it not make sense for us to have a well-defined phase and such that we define as constants? For example, if provider phase is "ready" or "Ready" or "OK", we would want to set ours to "Ready"? We could have another field that's providerPhase if we get an unknown value, and then set our phase to "Unknown". This basically needs to happen at some level anyway, but I wonder if it's not a better fit for our operator, rather than the UI which does a case-insensitive comparison in this case.

We did define the [phases](https://github.com/RHEcosystemAppEng/dbaas-operator/blob/5ba50619329599d46ec12a0c38c8751e8e3424fe/api/v1alpha1/dbaasprovider.go#L219-L225) for dbaas, which are used by crunchy and cockroach. 
But we didn't use validation to restrict the values. We could restrict the values with kubebuilder marker.
I am working on a [task](https://issues.redhat.com/browse/DBAAS-364) to support phases like `error` and `failed`. I'll add the marker when working on the task.

2022-03-04 02:56 UTC, xieshenzh commented on src/components/providerClusterProvisionPage.jsx
> +            if (instanceReadyCondition?.status.toLowerCase() === 'true') {
> @xieshenzh @jianrongzhang89 If the phase 'failed' we are checking provisionReadyCondition. Can the status of provisionReadyCondition can be something other than false? what about instanceReadyCondition?

We don't support phase `failed` currently. But I am working on a [task](https://issues.redhat.com/browse/DBAAS-364) to support that. In case of phase `failed`, the instance status ready condition is supposed to be false.